### ISSUE TITLE
Swipe to switch views instead on clicking on them.

### ISSUE THREAD

**Issue by Rishabh-More** [anazzubair/LoginConcept#1]
Hello, many thanks for converting Vasil Paliy's project to Kotlin. However I'm still a bit confused with the use of Animated view pager & conducter here. I noticed in your project that I need to click on the views to switch between the two views. While there's nothing wrong with that, when I handed it over to my friend for testing, he tried to swipe left first instead of clicking. I assume the concept to normal people seems like you need to swipe to switch between the views.

I however, am still unclear where & what changes in the code need to be made to enable switching between the views with swiping, while still having the option of clicking on it. As a kotlin noob, your insight on this issue will be very much appreciated!

**Comment by anazzubair** [comment]
I am no longer learning Android development. However, I had some free time today to spend fiddling with this. Check the latest commit and see if the AnimatedViewPager code changes help. If not, sorry buddy, you are on your own. Good luck with Android and Kotlin. 

[https://github.com/anazzubair/LoginConcept/commit/661754f51ce40ce1c526b8e3b0e6f792dd4a88a8](url)
